<?php

namespace GGG\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeNoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeNoticeRepository extends EntityRepository
{
}
