<?php

namespace GGG\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface
{

	public function loadUserByUserName($username){

	$user = $this->createQueryBuilder('u')
			->where('u.username = :username OR u.email = :email')
			->setParameter('username',$username)
			->setParameter('email',$username)
			->getQuery()
			->getOneOrNullResult();

			if( $user == null ){
				$message = sprintf('Il n\'y a pas d\'utilisateur correspondant à %s',$username);
				throw new UsernameNotFoundException($message);
			}
			return $user;
	}


	public function refreshUser(UserInterface $user){

		$class = get_class($user);

		if ( !$this->supportsClass($class) ){
			throw new UnsupportedUserException(sprintf('La classe "%s" n\'est pas conforme',$class));
		}

		return $this->find($user->getId());
	}

	
	public function supportsClass($class){

		if( $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName()) ){
			return true;
		}
		else{
			return false;
		}

	}


}
