<?php

namespace Proxies\__CG__\GGG\Bundle\NoticesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Appareil extends \GGG\Bundle\NoticesBundle\Entity\Appareil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'id', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'notice', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'categorie', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'marque', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'nom', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'anneeProd', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'photo', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'creation', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'description');
        }

        return array('__isInitialized__', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'id', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'notice', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'categorie', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'marque', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'nom', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'anneeProd', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'photo', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'creation', '' . "\0" . 'GGG\\Bundle\\NoticesBundle\\Entity\\Appareil' . "\0" . 'description');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Appareil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeProd($anneeProd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeProd', array($anneeProd));

        return parent::setAnneeProd($anneeProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeProd', array());

        return parent::getAnneeProd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', array($photo));

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', array());

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreation($creation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreation', array($creation));

        return parent::setCreation($creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreation', array());

        return parent::getCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotice(\GGG\Bundle\NoticesBundle\Entity\Notice $notice = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotice', array($notice));

        return parent::setNotice($notice);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotice', array());

        return parent::getNotice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\GGG\Bundle\NoticesBundle\Entity\Notice $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(\GGG\Bundle\NoticesBundle\Entity\Notice $marque = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', array($marque));

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', array());

        return parent::getMarque();
    }

}
