<?php

namespace GGG\Bundle\NoticesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeRepository extends EntityRepository
{
}
