#ggg_user_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: GGGUserBundle:Default:index }


ggg_user_inscription:
    pattern: /inscription
    defaults : { _controller: GGGUserBundle:Default:inscription }

ggg_user_desinscription:
    pattern: /desinscription
    defaults : { _controller: GGGUserBundle:Default:desinscription }

ggg_user_alerte:
    pattern: /alerte/{id}
    defaults: { _controller: GGGUserBundle:Default:alerte }